export const data = [
  {
    text: "React is being developed by Meta (formerly facebook)",
    source: "(Source)",
    btnText: "Technology",
    likes: 25,
    face: 10,
    dislikes: 4,
  },
  {
    text: "The shortest war in history lasted 38 minutes! It was between Britain and Zanzibar on August 27, 1896. It was over the ascension of the next Sultan in Zanzibar and resulted in a British victory.",
    source: "(Source)",
    btnText: "History",
    likes: 15,
    face: 8,
    dislikes: 2,
  },
  {
    text: "Millennial dads spend 3 times as much time with their kids than their fathers spent with them. In 1982, 43% of fathers had never changed a diaper. Today, that number is down to 3%",
    source: "(Source)",
    btnText: "Society",
    likes: 12,
    face: 2,
    dislikes: 0,
  },
  {
    text: "As of 2023, Breaking Bad is the highest-rated TV show on IMDb with a rating of 9.4/10",
    source: "(Source)",
    btnText: "Entertainment",
    likes: 11,
    face: 5,
    dislikes: 2,
  },
  {
    text: '"typewriter" is the longest English word you can type using 1 row of the QWERTY keyboard',
    source: "(Source)",
    btnText: "Technology",
    likes: 9,
    face: 1,
    dislikes: 0,
  },
  {
    text: "The shortest war in history lasted 38 minutes! It was between Britain and Zanzibar on August 27, 1896. It was over the ascension of the next Sultan in Zanzibar and resulted in a British victory.",
    source: "(Source)",
    btnText: "History",
    likes: 15,
    face: 8,
    dislikes: 2,
  },
  {
    text: "Millennial dads spend 3 times as much time with their kids than their fathers spent with them. In 1982, 43% of fathers had never changed a diaper. Today, that number is down to 3%",
    source: "(Source)",
    btnText: "Society",
    likes: 12,
    face: 2,
    dislikes: 0,
  },
  {
    text: "As of 2023, Breaking Bad is the highest-rated TV show on IMDb with a rating of 9.4/10",
    source: "(Source)",
    btnText: "Entertainment",
    likes: 11,
    face: 5,
    dislikes: 2,
  },
  {
    text: '"typewriter" is the longest English word you can type using 1 row of the QWERTY keyboard',
    source: "(Source)",
    btnText: "Technology",
    likes: 9,
    face: 1,
    dislikes: 0,
  },
];
